news_list:
    path:     /
    defaults: { _controller: AppBundle:News:index }
    methods:  [GET]

news_view:
    path:     /news/{id}
    defaults: { _controller: AppBundle:News:view }
    methods:  [GET]
    requirements:
        id: '\d+'

news_add:
    path:    /news/add
    defaults: { _controller: AppBundle:News:add }
    requirements:
        id: '\d+'

news_edit:
    path:    /news/{id}/edit
    defaults: { _controller: AppBundle:News:edit }
    requirements:
        id: '\d+'

news_delete:
    path:    /news/{id}/delete
    defaults: { _controller: AppBundle:News:remove }
    requirements:
        id: '\d+'

news_search:
    path:    /news/{id}/tag
    defaults: { _controller: AppBundle:News:search }
    requirements:
        id: '\d+'

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

security_login_check:
    path: /login-check
    defaults: { _controller: AppBundle:Security:loginCheck }

logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }
